var JsonDataFaker = require("./FakeData");
console.log(JsonDataFaker.name());
console.log(JsonDataFaker.firstName());
console.log(JsonDataFaker.lastName());
console.log(JsonDataFaker.username());
console.log(JsonDataFaker.email());
console.log(JsonDataFaker.ipv4());
console.log(JsonDataFaker.ipv4Local());
console.log(JsonDataFaker.emailDomain());
console.log(JsonDataFaker.domain());
console.log(JsonDataFaker.companyName());
console.log(JsonDataFaker.companyEmail());
